# Copyright (c) Instacertify
"""Custom field definitions for native ERPNext DocTypes."""

from __future__ import annotations

LEAD_FIELDS = [
	{
		"fieldname": "ic_section_company_extra",
		"fieldtype": "Section Break",
		"label": "Instacertify Company Details",
		"insert_after": "notes",
	},
	{
		"fieldname": "ic_factory_address",
		"fieldtype": "Small Text",
		"label": "Factory Address",
		"insert_after": "ic_section_company_extra",
	},
	{
		"fieldname": "ic_company_size",
		"fieldtype": "Select",
		"label": "Company Size",
		"options": "\nMicro\nSmall\nMedium\nLarge",
		"insert_after": "ic_factory_address",
	},
	{
		"fieldname": "ic_column_break_1",
		"fieldtype": "Column Break",
		"insert_after": "ic_company_size",
	},
	{
		"fieldname": "ic_gst_number",
		"fieldtype": "Data",
		"label": "GST Number",
		"insert_after": "ic_column_break_1",
		"depends_on": "eval:doc.country=='India'",
	},
	{
		"fieldname": "ic_state",
		"fieldtype": "Data",
		"label": "State",
		"insert_after": "ic_gst_number",
		"depends_on": "eval:doc.country=='India'",
	},
	{
		"fieldname": "ic_section_request",
		"fieldtype": "Section Break",
		"label": "Request & Source",
		"insert_after": "ic_state",
	},
	{
		"fieldname": "ic_request_category",
		"fieldtype": "Select",
		"label": "Request Category",
		"options": "\nService Request\nTesting Request\nCertification Request\nOther",
		"insert_after": "ic_section_request",
		"in_list_view": 1,
	},
	{
		"fieldname": "ic_lead_source_detail",
		"fieldtype": "Select",
		"label": "Lead Source Detail",
		"options": "\nGoogle\nDirect Call\nLead Generated\nReferral by Existing Customer\nIndiaMART\nExisting Customer\nOther",
		"insert_after": "ic_request_category",
	},
	{
		"fieldname": "ic_consultant_referral",
		"fieldtype": "Link",
		"label": "Consultant / Referral Person",
		"options": "Consultant Referral",
		"insert_after": "ic_lead_source_detail",
	},
	{
		"fieldname": "ic_column_break_2",
		"fieldtype": "Column Break",
		"insert_after": "ic_consultant_referral",
	},
	{
		"fieldname": "ic_expected_timeline",
		"fieldtype": "Data",
		"label": "Expected Timeline",
		"insert_after": "ic_column_break_2",
	},
	{
		"fieldname": "ic_estimated_value",
		"fieldtype": "Currency",
		"label": "Estimated Value",
		"insert_after": "ic_expected_timeline",
	},
	{
		"fieldname": "ic_priority",
		"fieldtype": "Select",
		"label": "Priority",
		"options": "\nLow\nMedium\nHigh\nUrgent",
		"default": "Medium",
		"insert_after": "ic_estimated_value",
	},
	{
		"fieldname": "ic_assigned_salesperson",
		"fieldtype": "Link",
		"label": "Assigned Salesperson",
		"options": "User",
		"insert_after": "ic_priority",
	},
	{
		"fieldname": "ic_assigned_operations_manager",
		"fieldtype": "Link",
		"label": "Assigned Operations Manager",
		"options": "User",
		"insert_after": "ic_assigned_salesperson",
	},
	{
		"fieldname": "ic_remarks",
		"fieldtype": "Text Editor",
		"label": "Instacertify Remarks",
		"insert_after": "ic_assigned_operations_manager",
	},
	{
		"fieldname": "ic_alternate_phone",
		"fieldtype": "Data",
		"label": "Alternate Contact Number",
		"options": "Phone",
		"insert_after": "mobile_no",
	},
]

CUSTOMER_FIELDS = [
	{
		"fieldname": "ic_section_profile",
		"fieldtype": "Section Break",
		"label": "Instacertify Profile",
		"insert_after": "tax_id",
	},
	{
		"fieldname": "ic_gst_number",
		"fieldtype": "Data",
		"label": "GST Number",
		"insert_after": "ic_section_profile",
	},
	{
		"fieldname": "ic_factory_address",
		"fieldtype": "Small Text",
		"label": "Factory Address",
		"insert_after": "ic_gst_number",
	},
	{
		"fieldname": "ic_column_break_1",
		"fieldtype": "Column Break",
		"insert_after": "ic_factory_address",
	},
	{
		"fieldname": "ic_country",
		"fieldtype": "Link",
		"label": "Country",
		"options": "Country",
		"insert_after": "ic_column_break_1",
	},
	{
		"fieldname": "ic_state",
		"fieldtype": "Data",
		"label": "State",
		"insert_after": "ic_country",
	},
	{
		"fieldname": "ic_date_onboarded",
		"fieldtype": "Date",
		"label": "Date Onboarded",
		"insert_after": "ic_state",
	},
	{
		"fieldname": "ic_company_size",
		"fieldtype": "Select",
		"label": "Company Size",
		"options": "\nMicro\nSmall\nMedium\nLarge",
		"insert_after": "ic_date_onboarded",
	},
	{
		"fieldname": "ic_primary_currency",
		"fieldtype": "Link",
		"label": "Preferred Currency",
		"options": "Currency",
		"insert_after": "ic_company_size",
	},
	{
		"fieldname": "ic_section_history",
		"fieldtype": "Section Break",
		"label": "Customer History Overview",
		"insert_after": "ic_primary_currency",
	},
	{
		"fieldname": "ic_history_html",
		"fieldtype": "HTML",
		"label": "History",
		"insert_after": "ic_section_history",
	},
]

QUOTATION_FIELDS = [
	{
		"fieldname": "ic_section_type",
		"fieldtype": "Section Break",
		"label": "Instacertify Quotation Type",
		"insert_after": "order_type",
	},
	{
		"fieldname": "ic_quotation_type",
		"fieldtype": "Select",
		"label": "Quotation Type",
		"options": "\nService\nTesting\nOther\nMultiple Products / Multiple Services",
		"reqd": 1,
		"insert_after": "ic_section_type",
		"in_list_view": 1,
	},
	{
		"fieldname": "ic_quotation_template",
		"fieldtype": "Link",
		"label": "Quotation Template",
		"options": "IC Quotation Template",
		"insert_after": "ic_quotation_type",
	},
	{
		"fieldname": "ic_column_break_type",
		"fieldtype": "Column Break",
		"insert_after": "ic_quotation_template",
	},
	{
		"fieldname": "ic_revision_number",
		"fieldtype": "Int",
		"label": "Revision Number",
		"default": 0,
		"insert_after": "ic_column_break_type",
	},
	{
		"fieldname": "ic_workflow_status",
		"fieldtype": "Select",
		"label": "Customer Workflow Status",
		"options": "Draft\nInternal Review\nReady to Share\nShared with Customer\nCustomer Review\nAccepted\nChanges Requested\nRejected / Lost",
		"default": "Draft",
		"insert_after": "ic_revision_number",
		"in_list_view": 1,
	},
	{
		"fieldname": "ic_share_token",
		"fieldtype": "Data",
		"label": "Share Token",
		"read_only": 1,
		"hidden": 1,
		"insert_after": "ic_workflow_status",
	},
	{
		"fieldname": "ic_shared_on",
		"fieldtype": "Datetime",
		"label": "Shared On",
		"read_only": 1,
		"insert_after": "ic_share_token",
	},
	{
		"fieldname": "ic_customer_remarks",
		"fieldtype": "Small Text",
		"label": "Customer Remarks",
		"read_only": 1,
		"insert_after": "ic_shared_on",
	},
	{
		"fieldname": "ic_qr_code",
		"fieldtype": "Attach Image",
		"label": "QR Code",
		"read_only": 1,
		"insert_after": "ic_customer_remarks",
	},
	{
		"fieldname": "ic_section_service",
		"fieldtype": "Section Break",
		"label": "Service / Certification Details",
		"insert_after": "ic_qr_code",
		"depends_on": "eval:in_list(['Service','Other','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
	},
	{
		"fieldname": "ic_service_name",
		"fieldtype": "Data",
		"label": "Service Name",
		"insert_after": "ic_section_service",
	},
	{
		"fieldname": "ic_certification_type",
		"fieldtype": "Data",
		"label": "Certification Type",
		"insert_after": "ic_service_name",
	},
	{
		"fieldname": "ic_applicable_standard",
		"fieldtype": "Data",
		"label": "Applicable Standard",
		"insert_after": "ic_certification_type",
	},
	{
		"fieldname": "ic_column_break_svc",
		"fieldtype": "Column Break",
		"insert_after": "ic_applicable_standard",
	},
	{
		"fieldname": "ic_estimated_timeline",
		"fieldtype": "Data",
		"label": "Estimated Certification Timeline",
		"insert_after": "ic_column_break_svc",
	},
	{
		"fieldname": "ic_scope_of_work",
		"fieldtype": "Text Editor",
		"label": "Scope of Work",
		"insert_after": "ic_estimated_timeline",
	},
	{
		"fieldname": "ic_deliverables",
		"fieldtype": "Text Editor",
		"label": "Deliverables",
		"insert_after": "ic_scope_of_work",
	},
	{
		"fieldname": "ic_section_costing",
		"fieldtype": "Section Break",
		"label": "Cost Breakdown (Revenue vs Pass-Through)",
		"insert_after": "ic_deliverables",
	},
	{
		"fieldname": "ic_cost_items",
		"fieldtype": "Table",
		"label": "Cost Items",
		"options": "IC Quotation Cost Item",
		"insert_after": "ic_section_costing",
	},
	{
		"fieldname": "ic_commercial_value",
		"fieldtype": "Currency",
		"label": "Instacertify Commercial Value",
		"read_only": 1,
		"insert_after": "ic_cost_items",
		"options": "currency",
	},
	{
		"fieldname": "ic_passthrough_value",
		"fieldtype": "Currency",
		"label": "External / Pass-Through Charges",
		"read_only": 1,
		"insert_after": "ic_commercial_value",
		"options": "currency",
	},
	{
		"fieldname": "ic_total_quoted_value",
		"fieldtype": "Currency",
		"label": "Total Quoted Value",
		"read_only": 1,
		"insert_after": "ic_passthrough_value",
		"options": "currency",
	},
	{
		"fieldname": "ic_section_testing",
		"fieldtype": "Section Break",
		"label": "Testing Details",
		"insert_after": "ic_total_quoted_value",
		"depends_on": "eval:in_list(['Testing','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
	},
	{
		"fieldname": "ic_subject",
		"fieldtype": "Data",
		"label": "Subject",
		"default": "Testing",
		"insert_after": "ic_section_testing",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_about_testing",
		"fieldtype": "Text Editor",
		"label": "ABOUT (Testing Scope)",
		"insert_after": "ic_subject",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_applicable_standards_text",
		"fieldtype": "Text Editor",
		"label": "Applicable Standards (Narrative)",
		"insert_after": "ic_about_testing",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_samples_note",
		"fieldtype": "Small Text",
		"label": "Samples Note",
		"default": "Note: Additional samples may be requested by the laboratory depending on the product configuration and applicable test requirements.",
		"insert_after": "ic_applicable_standards_text",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_gst_note",
		"fieldtype": "Data",
		"label": "GST Note",
		"default": "Note: GST @ 18% shall be charged additionally on the above testing charges.",
		"insert_after": "ic_samples_note",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_test_items",
		"fieldtype": "Table",
		"label": "Commercials / Test Entries",
		"options": "IC Quotation Test Item",
		"insert_after": "ic_gst_note",
	},
	{
		"fieldname": "ic_payment_terms",
		"fieldtype": "Text Editor",
		"label": "Payment Terms",
		"insert_after": "ic_test_items",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_sample_handling_policy",
		"fieldtype": "Text Editor",
		"label": "Sample Handling & Disposal Policy",
		"insert_after": "ic_payment_terms",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_cancellation_policy",
		"fieldtype": "Text Editor",
		"label": "Cancellation & Refund Policy",
		"insert_after": "ic_sample_handling_policy",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_confidentiality",
		"fieldtype": "Text Editor",
		"label": "Confidentiality & Data Protection",
		"insert_after": "ic_cancellation_policy",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_section_products",
		"fieldtype": "Section Break",
		"label": "Multi-Product / Multi-Service",
		"insert_after": "ic_confidentiality",
		"depends_on": "eval:doc.ic_quotation_type=='Multiple Products / Multiple Services'",
	},
	{
		"fieldname": "ic_products",
		"fieldtype": "Table",
		"label": "Products & Services",
		"options": "IC Quotation Product",
		"insert_after": "ic_section_products",
	},
	{
		"fieldname": "ic_section_terms",
		"fieldtype": "Section Break",
		"label": "Terms & Force Majeure",
		"insert_after": "ic_products",
	},
	{
		"fieldname": "ic_terms_and_conditions",
		"fieldtype": "Text Editor",
		"label": "Terms and Conditions",
		"insert_after": "ic_section_terms",
	},
	{
		"fieldname": "ic_force_majeure",
		"fieldtype": "Text Editor",
		"label": "Force Majeure",
		"insert_after": "ic_terms_and_conditions",
	},
	{
		"fieldname": "ic_parent_quotation",
		"fieldtype": "Link",
		"label": "Parent Quotation (Revision Of)",
		"options": "Quotation",
		"insert_after": "ic_force_majeure",
	},
]

PROJECT_FIELDS = [
	{
		"fieldname": "ic_section_stage",
		"fieldtype": "Section Break",
		"label": "Instacertify Project Stage",
		"insert_after": "project_name",
	},
	{
		"fieldname": "ic_project_stage",
		"fieldtype": "Select",
		"label": "Project Stage",
		"options": "Project Initiated\nCustomer Documents Pending\nDocuments Under Review\nApplication Submitted\nSample Awaited\nSample Received\nSample Dispatched to Laboratory\nTesting in Progress\nReport Awaited\nReport Available\nCertification in Progress\nCertificate Available\nDelivered to Customer\nProject Completed",
		"default": "Project Initiated",
		"in_list_view": 1,
		"insert_after": "ic_section_stage",
	},
	{
		"fieldname": "ic_priority",
		"fieldtype": "Select",
		"label": "Priority",
		"options": "Low\nMedium\nHigh\nUrgent",
		"default": "Medium",
		"insert_after": "ic_project_stage",
		"in_list_view": 1,
	},
	{
		"fieldname": "ic_column_break_1",
		"fieldtype": "Column Break",
		"insert_after": "ic_priority",
	},
	{
		"fieldname": "ic_pending_action",
		"fieldtype": "Data",
		"label": "Pending Action",
		"insert_after": "ic_column_break_1",
	},
	{
		"fieldname": "ic_progress_percentage",
		"fieldtype": "Percent",
		"label": "Progress Percentage",
		"insert_after": "ic_pending_action",
	},
	{
		"fieldname": "ic_assigned_employee",
		"fieldtype": "Link",
		"label": "Assigned Employee",
		"options": "User",
		"insert_after": "ic_progress_percentage",
	},
	{
		"fieldname": "ic_deadline",
		"fieldtype": "Date",
		"label": "Deadline",
		"insert_after": "ic_assigned_employee",
	},
	{
		"fieldname": "ic_quotation",
		"fieldtype": "Link",
		"label": "Source Quotation",
		"options": "Quotation",
		"insert_after": "ic_deadline",
	},
	{
		"fieldname": "ic_section_tracker",
		"fieldtype": "Section Break",
		"label": "Progress Tracker",
		"insert_after": "ic_quotation",
	},
	{
		"fieldname": "ic_progress_html",
		"fieldtype": "HTML",
		"label": "Progress",
		"insert_after": "ic_section_tracker",
	},
	{
		"fieldname": "ic_products_services",
		"fieldtype": "Small Text",
		"label": "Products / Services",
		"insert_after": "ic_progress_html",
	},
	{
		"fieldname": "ic_deliverables",
		"fieldtype": "Small Text",
		"label": "Deliverables",
		"insert_after": "ic_products_services",
	},
	{
		"fieldname": "ic_testing_requirements",
		"fieldtype": "Small Text",
		"label": "Testing Requirements",
		"insert_after": "ic_deliverables",
	},
]

SALES_INVOICE_FIELDS = [
	{
		"fieldname": "ic_qr_code",
		"fieldtype": "Attach Image",
		"label": "QR Code",
		"read_only": 1,
		"insert_after": "customer_name",
	},
	{
		"fieldname": "ic_project",
		"fieldtype": "Link",
		"label": "Project",
		"options": "Project",
		"insert_after": "project",
	},
]

ASSET_FIELDS = [
	{
		"fieldname": "ic_current_holder",
		"fieldtype": "Link",
		"label": "Current Holder",
		"options": "Employee",
		"insert_after": "custodian",
	},
]

CUSTOM_FIELDS = {
	"Lead": LEAD_FIELDS,
	"Customer": CUSTOMER_FIELDS,
	"Quotation": QUOTATION_FIELDS,
	"Project": PROJECT_FIELDS,
	"Sales Invoice": SALES_INVOICE_FIELDS,
	"Asset": ASSET_FIELDS,
}
