# Copyright (c) Instacertify
"""Custom field definitions for native ERPNext DocTypes."""

from __future__ import annotations

LEAD_FIELDS = [
	{
		"fieldname": "ic_section_capture",
		"fieldtype": "Section Break",
		"label": "Lead Capture",
		"insert_after": "salutation",
	},
	{
		"fieldname": "ic_party_name",
		"fieldtype": "Data",
		"label": "Name / company",
		"reqd": 1,
		"in_list_view": 1,
		"insert_after": "ic_section_capture",
		"description": "Person or firm — enough to get started",
	},
	{
		"fieldname": "ic_column_capture",
		"fieldtype": "Column Break",
		"insert_after": "ic_party_name",
	},
	{
		"fieldname": "ic_company_size",
		"fieldtype": "Select",
		"label": "Company Size",
		"options": "\nMicro\nSmall\nMedium\nLarge",
		"insert_after": "ic_column_capture",
	},
	{
		"fieldname": "ic_section_company_extra",
		"fieldtype": "Section Break",
		"label": "Instacertify Company Details",
		"insert_after": "notes",
	},
	{
		"fieldname": "ic_factory_address",
		"fieldtype": "Small Text",
		"label": "Factory Address",
		"insert_after": "ic_section_company_extra",
	},
	{
		"fieldname": "ic_column_break_1",
		"fieldtype": "Column Break",
		"insert_after": "ic_factory_address",
	},
	{
		"fieldname": "ic_gst_number",
		"fieldtype": "Data",
		"label": "GST Number",
		"insert_after": "ic_column_break_1",
		"depends_on": "eval:doc.country=='India'",
	},
	{
		"fieldname": "ic_state",
		"fieldtype": "Data",
		"label": "State",
		"insert_after": "ic_gst_number",
		"depends_on": "eval:doc.country=='India'",
	},
	{
		"fieldname": "ic_section_request",
		"fieldtype": "Section Break",
		"label": "Request & Source",
		"insert_after": "ic_state",
	},
	{
		"fieldname": "ic_project_type",
		"fieldtype": "Link",
		"label": "Project Type",
		"options": "IC Project Type",
		"insert_after": "ic_section_request",
		"in_list_view": 1,
		"description": "BIS, Testing, EPR, LMPC, SABER, GMARK, MSDS Authoring — editable in Project Type",
	},
	{
		"fieldname": "ic_request_category",
		"fieldtype": "Select",
		"label": "Request Category",
		"options": "\nService Request\nTesting Request\nCertification Request\nOther",
		"insert_after": "ic_project_type",
	},
	{
		"fieldname": "ic_lead_source_detail",
		"fieldtype": "Link",
		"label": "Lead Source",
		"options": "IC Lead Source",
		"insert_after": "ic_request_category",
		"in_list_view": 1,
		"description": "Editable master — Lead Source (Google Search, Ads, IndiaMART, Reference, Consultant, …)",
	},
	{
		"fieldname": "ic_consultant_referral",
		"fieldtype": "Link",
		"label": "Consultant / Referral Person",
		"options": "Consultant Referral",
		"insert_after": "ic_lead_source_detail",
		"depends_on": "eval:doc.ic_lead_source_detail=='Consultant' || doc.ic_lead_source_detail=='Reference'",
	},
	{
		"fieldname": "ic_column_break_2",
		"fieldtype": "Column Break",
		"insert_after": "ic_consultant_referral",
	},
	{
		"fieldname": "ic_expected_timeline",
		"fieldtype": "Data",
		"label": "Expected Timeline",
		"insert_after": "ic_column_break_2",
	},
	{
		"fieldname": "ic_estimated_value",
		"fieldtype": "Currency",
		"label": "Estimated Value",
		"insert_after": "ic_expected_timeline",
	},
	{
		"fieldname": "ic_priority",
		"fieldtype": "Select",
		"label": "Priority",
		"options": "\nLow\nMedium\nHigh\nUrgent",
		"default": "Medium",
		"insert_after": "ic_estimated_value",
	},
	{
		"fieldname": "ic_assigned_salesperson",
		"fieldtype": "Link",
		"label": "Assigned Salesperson",
		"options": "User",
		"insert_after": "ic_priority",
	},
	{
		"fieldname": "ic_assigned_operations_manager",
		"fieldtype": "Link",
		"label": "Assigned Operations Manager",
		"options": "User",
		"insert_after": "ic_assigned_salesperson",
	},
	{
		"fieldname": "ic_remarks",
		"fieldtype": "Text Editor",
		"label": "Instacertify Remarks",
		"insert_after": "ic_assigned_operations_manager",
	},
	{
		"fieldname": "ic_section_followup",
		"fieldtype": "Section Break",
		"label": "Follow-up / Calls",
		"insert_after": "ic_remarks",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_next_contact_date",
		"fieldtype": "Date",
		"label": "Next Contact Date",
		"insert_after": "ic_section_followup",
		"in_list_view": 1,
		"in_standard_filter": 1,
		"description": "Shown as a contact prompt on Instacertify Home when due",
	},
	{
		"fieldname": "ic_last_contacted",
		"fieldtype": "Date",
		"label": "Last Contacted",
		"insert_after": "ic_next_contact_date",
	},
	{
		"fieldname": "ic_column_followup",
		"fieldtype": "Column Break",
		"insert_after": "ic_last_contacted",
	},
	{
		"fieldname": "ic_call_remarks",
		"fieldtype": "Small Text",
		"label": "What they need",
		"insert_after": "ic_column_followup",
		"in_list_view": 1,
		"description": "One line is fine — fill more later",
	},
	{
		"fieldname": "ic_lead_connected",
		"fieldtype": "Check",
		"label": "Lead Connected",
		"insert_after": "ic_call_remarks",
		"in_list_view": 1,
		"description": "Mark when a live conversation happened",
	},
	{
		"fieldname": "ic_section_pipeline",
		"fieldtype": "Section Break",
		"label": "Sales Pipeline",
		"insert_after": "ic_lead_connected",
	},
	{
		"fieldname": "ic_pipeline_stage",
		"fieldtype": "Select",
		"label": "Pipeline Stage",
		"options": "Lead\nRequirement Analysis\nTechnical Review\nQuote\nNegotiation\nOrder\nProject / Case\nCertification\nRenewal",
		"default": "Lead",
		"in_list_view": 1,
		"in_standard_filter": 1,
		"insert_after": "ic_section_pipeline",
		"description": "Lead → Requirement Analysis → Technical Review → Quote → Negotiation → Order → Project/Case → Certification → Renewal",
	},
	{
		"fieldname": "ic_alternate_phone",
		"fieldtype": "Data",
		"label": "Alternate Contact Number",
		"options": "Phone",
		"insert_after": "mobile_no",
	},
	{
		"fieldname": "ic_related_tab",
		"fieldtype": "Tab Break",
		"label": "Related Data",
		"insert_after": "ic_pipeline_stage",
	},
	{
		"fieldname": "ic_section_history",
		"fieldtype": "Section Break",
		"label": "Lead Journey Overview",
		"insert_after": "ic_related_tab",
	},
	{
		"fieldname": "ic_history_html",
		"fieldtype": "HTML",
		"label": "History",
		"insert_after": "ic_section_history",
	},
]

CUSTOMER_FIELDS = [
	{
		"fieldname": "ic_section_profile",
		"fieldtype": "Section Break",
		"label": "Instacertify Profile",
		"insert_after": "tax_id",
	},
	{
		"fieldname": "ic_gst_number",
		"fieldtype": "Data",
		"label": "GST Number",
		"insert_after": "ic_section_profile",
	},
	{
		"fieldname": "ic_factory_address",
		"fieldtype": "Small Text",
		"label": "Factory Address",
		"insert_after": "ic_gst_number",
	},
	{
		"fieldname": "ic_column_break_1",
		"fieldtype": "Column Break",
		"insert_after": "ic_factory_address",
	},
	{
		"fieldname": "ic_country",
		"fieldtype": "Link",
		"label": "Country",
		"options": "Country",
		"insert_after": "ic_column_break_1",
	},
	{
		"fieldname": "ic_state",
		"fieldtype": "Data",
		"label": "State",
		"insert_after": "ic_country",
	},
	{
		"fieldname": "ic_date_onboarded",
		"fieldtype": "Date",
		"label": "Date Onboarded",
		"insert_after": "ic_state",
	},
	{
		"fieldname": "ic_company_size",
		"fieldtype": "Select",
		"label": "Company Size",
		"options": "\nMicro\nSmall\nMedium\nLarge",
		"insert_after": "ic_date_onboarded",
	},
	{
		"fieldname": "ic_primary_currency",
		"fieldtype": "Link",
		"label": "Preferred Currency",
		"options": "Currency",
		"insert_after": "ic_company_size",
		"description": "Auto USD when Country is not India; change anytime to INR or another currency.",
	},
	{
		"fieldname": "ic_currency_manual",
		"fieldtype": "Check",
		"label": "Currency Manually Set",
		"insert_after": "ic_primary_currency",
		"description": "When checked, country changes will not overwrite billing currency.",
		"default": "0",
	},
	{
		"fieldname": "ic_related_tab",
		"fieldtype": "Tab Break",
		"label": "Related Data",
		"insert_after": "column_break_hdmn",
	},
	{
		"fieldname": "ic_section_history",
		"fieldtype": "Section Break",
		"label": "Customer History Overview",
		"insert_after": "ic_related_tab",
	},
	{
		"fieldname": "ic_history_html",
		"fieldtype": "HTML",
		"label": "History",
		"insert_after": "ic_section_history",
	},
	{
		"fieldname": "ic_section_files",
		"fieldtype": "Section Break",
		"label": "Completed Project Files",
		"insert_after": "ic_history_html",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_customer_files_html",
		"fieldtype": "HTML",
		"label": "Customer Files",
		"insert_after": "ic_section_files",
	},
]

QUOTATION_FIELDS = [
	{
		"fieldname": "ic_currency_manual",
		"fieldtype": "Check",
		"label": "Currency Manually Set",
		"insert_after": "currency",
		"description": "Stops auto USD/INR switch from customer country. Clear to re-enable auto billing currency.",
		"default": "0",
	},
	{
		"fieldname": "ic_tax_manual",
		"fieldtype": "Check",
		"label": "Tax Template Manually Set",
		"insert_after": "taxes_and_charges",
		"description": "Stops auto GST In-state / Out-state / Export tax template selection.",
		"default": "0",
	},
	# --- 1. Setup: type + template side-by-side (stretched selects) ---
	{
		"fieldname": "ic_section_type",
		"fieldtype": "Section Break",
		"label": "1. Quotation Setup — Type & Template",
		"insert_after": "order_type",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_entry_guide",
		"fieldtype": "HTML",
		"label": "Entry Guide",
		"insert_after": "ic_section_type",
	},
	{
		"fieldname": "ic_quotation_type",
		"fieldtype": "Select",
		"label": "Quotation Type",
		"options": "\nConsulting\nTesting\nRenewal\nOther\nMultiple Products / Multiple Services\nService",
		"reqd": 1,
		"insert_after": "ic_entry_guide",
		"in_list_view": 1,
		"bold": 1,
		"description": "Required. Consulting / Service = certification quotes · Testing = lab commercials · Renewal = renewals · Multiple = mixed lines.",
	},
	{
		"fieldname": "ic_column_break_type",
		"fieldtype": "Column Break",
		"insert_after": "ic_quotation_type",
	},
	{
		"fieldname": "ic_quotation_template",
		"fieldtype": "Link",
		"label": "Quotation Template",
		"options": "IC Quotation Template",
		"insert_after": "ic_column_break_type",
		"bold": 1,
		"description": "Optional. Filtered by type above — fills About, terms, commercials, and policies in one click.",
	},
	# --- 2. Identity ---
	{
		"fieldname": "ic_section_identity",
		"fieldtype": "Section Break",
		"label": "2. Quote Identity & Status",
		"insert_after": "ic_quotation_template",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_service_family",
		"fieldtype": "Data",
		"label": "Service Family / Subtype",
		"insert_after": "ic_section_identity",
		"description": "e.g. BIS CRS, TEC, EMC, Safety, BIS Renewal",
	},
	{
		"fieldname": "ic_quote_number",
		"fieldtype": "Data",
		"label": "Quote No (Print)",
		"description": "Printed number, e.g. ILPL/C/2026-2027/130. Leave blank to use document name.",
		"insert_after": "ic_service_family",
	},
	{
		"fieldname": "ic_column_identity",
		"fieldtype": "Column Break",
		"insert_after": "ic_quote_number",
	},
	{
		"fieldname": "ic_revision_number",
		"fieldtype": "Int",
		"label": "Revision Number",
		"default": 0,
		"insert_after": "ic_column_identity",
	},
	{
		"fieldname": "ic_workflow_status",
		"fieldtype": "Select",
		"label": "Customer Workflow Status",
		"options": "Draft\nInternal Review\nReady to Share\nShared with Customer\nCustomer Review\nAccepted\nChanges Requested\nRejected / Lost",
		"default": "Draft",
		"insert_after": "ic_revision_number",
		"in_list_view": 1,
		"bold": 1,
	},
	{
		"fieldname": "ic_post_accept_action",
		"fieldtype": "Select",
		"label": "After Customer Accepts",
		"options": "\nUse Company Default\nCreate Invoice\nCreate Project\nCreate Invoice and Project\nManual",
		"default": "Use Company Default",
		"insert_after": "ic_workflow_status",
		"description": "Auto-create invoice and/or project when the customer accepts.",
	},
	# --- Customer share (secondary) ---
	{
		"fieldname": "ic_section_share",
		"fieldtype": "Section Break",
		"label": "Customer Share Status",
		"insert_after": "ic_post_accept_action",
		"collapsible": 1,
		"collapsible_depends_on": "eval:doc.ic_workflow_status!='Draft'",
	},
	{
		"fieldname": "ic_share_token",
		"fieldtype": "Data",
		"label": "Share Token",
		"read_only": 1,
		"hidden": 1,
		"insert_after": "ic_section_share",
	},
	{
		"fieldname": "ic_shared_on",
		"fieldtype": "Datetime",
		"label": "Shared On",
		"read_only": 1,
		"insert_after": "ic_share_token",
	},
	{
		"fieldname": "ic_customer_remarks",
		"fieldtype": "Small Text",
		"label": "Customer Remarks",
		"read_only": 1,
		"insert_after": "ic_shared_on",
	},
	{
		"fieldname": "ic_column_share",
		"fieldtype": "Column Break",
		"insert_after": "ic_customer_remarks",
	},
	{
		"fieldname": "ic_qr_code",
		"fieldtype": "Attach Image",
		"label": "QR Code",
		"read_only": 1,
		"insert_after": "ic_column_share",
	},
	# --- 3. Consulting basics (two columns) ---
	{
		"fieldname": "ic_section_service",
		"fieldtype": "Section Break",
		"label": "3. Consulting / Service Basics",
		"insert_after": "ic_qr_code",
		"depends_on": "eval:in_list(['Consulting','Renewal','Service','Other','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_service_name",
		"fieldtype": "Data",
		"label": "Service / Consultancy Title",
		"insert_after": "ic_section_service",
		"bold": 1,
	},
	{
		"fieldname": "ic_certification_type",
		"fieldtype": "Data",
		"label": "Certification Type",
		"insert_after": "ic_service_name",
	},
	{
		"fieldname": "ic_applicable_standard",
		"fieldtype": "Data",
		"label": "Applicable Standard",
		"insert_after": "ic_certification_type",
	},
	{
		"fieldname": "ic_column_break_svc",
		"fieldtype": "Column Break",
		"insert_after": "ic_applicable_standard",
	},
	{
		"fieldname": "ic_estimated_timeline",
		"fieldtype": "Data",
		"label": "Estimated Certification Timeline",
		"insert_after": "ic_column_break_svc",
		"description": "e.g. 4–6 weeks from document clearance",
	},
	{
		"fieldname": "ic_validity_days",
		"fieldtype": "Int",
		"label": "Quotation Validity (Days)",
		"default": 90,
		"insert_after": "ic_estimated_timeline",
	},
	# --- Consulting narrative — separate sections so fields are stretched ---
	{
		"fieldname": "ic_section_about",
		"fieldtype": "Section Break",
		"label": "4. About, Standards & Process",
		"insert_after": "ic_validity_days",
		"depends_on": "eval:in_list(['Consulting','Renewal','Service','Other','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_about_service",
		"fieldtype": "Text Editor",
		"label": "ABOUT (Consulting)",
		"insert_after": "ic_section_about",
	},
	{
		"fieldname": "ic_standard_narrative",
		"fieldtype": "Text Editor",
		"label": "Standard Applicable (Narrative)",
		"insert_after": "ic_about_service",
	},
	{
		"fieldname": "ic_process_steps",
		"fieldtype": "Text Editor",
		"label": "Process Steps",
		"insert_after": "ic_standard_narrative",
	},
	{
		"fieldname": "ic_section_docs_timeline",
		"fieldtype": "Section Break",
		"label": "5. Validity, Samples & Documents",
		"insert_after": "ic_process_steps",
		"depends_on": "eval:in_list(['Consulting','Renewal','Service','Other','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_validity_text",
		"fieldtype": "Text Editor",
		"label": "Validity of Registration / Service",
		"insert_after": "ic_section_docs_timeline",
	},
	{
		"fieldname": "ic_timeline_details",
		"fieldtype": "Text Editor",
		"label": "Timelines (Detailed)",
		"insert_after": "ic_validity_text",
	},
	{
		"fieldname": "ic_sample_required",
		"fieldtype": "Text Editor",
		"label": "Sample Required",
		"insert_after": "ic_timeline_details",
	},
	{
		"fieldname": "ic_documents_required",
		"fieldtype": "Text Editor",
		"label": "Documents Required",
		"insert_after": "ic_sample_required",
	},
	{
		"fieldname": "ic_section_scope",
		"fieldtype": "Section Break",
		"label": "6. Scope, Deliverables & Commercial Notes",
		"insert_after": "ic_documents_required",
		"depends_on": "eval:in_list(['Consulting','Renewal','Service','Other','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_commercials_notes",
		"fieldtype": "Text Editor",
		"label": "Commercials Notes",
		"insert_after": "ic_section_scope",
	},
	{
		"fieldname": "ic_scope_of_work",
		"fieldtype": "Text Editor",
		"label": "Scope of Work (Additional)",
		"insert_after": "ic_commercials_notes",
	},
	{
		"fieldname": "ic_deliverables",
		"fieldtype": "Text Editor",
		"label": "Deliverables",
		"insert_after": "ic_scope_of_work",
	},
	{
		"fieldname": "ic_section_costing",
		"fieldtype": "Section Break",
		"label": "7. Cost Breakdown / Commercials",
		"insert_after": "ic_deliverables",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_cost_items",
		"fieldtype": "Table",
		"label": "Cost Items / Commercials",
		"options": "IC Quotation Cost Item",
		"insert_after": "ic_section_costing",
		"description": "Add each fee line (Instacertify fee vs pass-through). Totals update below.",
	},
	{
		"fieldname": "ic_section_cost_totals",
		"fieldtype": "Section Break",
		"label": "Commercial Totals",
		"insert_after": "ic_cost_items",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_commercial_value",
		"fieldtype": "Currency",
		"label": "Commercial Value",
		"read_only": 1,
		"insert_after": "ic_section_cost_totals",
		"options": "currency",
	},
	{
		"fieldname": "ic_column_totals_2",
		"fieldtype": "Column Break",
		"insert_after": "ic_commercial_value",
	},
	{
		"fieldname": "ic_passthrough_value",
		"fieldtype": "Currency",
		"label": "External / Pass-Through Charges",
		"read_only": 1,
		"insert_after": "ic_column_totals_2",
		"options": "currency",
	},
	{
		"fieldname": "ic_column_totals_3",
		"fieldtype": "Column Break",
		"insert_after": "ic_passthrough_value",
	},
	{
		"fieldname": "ic_total_quoted_value",
		"fieldtype": "Currency",
		"label": "Total Quoted Value",
		"read_only": 1,
		"bold": 1,
		"insert_after": "ic_column_totals_3",
		"options": "currency",
	},
	# --- Testing ---
	{
		"fieldname": "ic_section_testing",
		"fieldtype": "Section Break",
		"label": "3. Testing Details",
		"insert_after": "ic_total_quoted_value",
		"depends_on": "eval:in_list(['Testing','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_subject",
		"fieldtype": "Data",
		"label": "Subject",
		"default": "Testing",
		"insert_after": "ic_section_testing",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
		"bold": 1,
	},
	{
		"fieldname": "ic_about_testing",
		"fieldtype": "Text Editor",
		"label": "ABOUT (Testing Scope)",
		"insert_after": "ic_subject",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_applicable_standards_text",
		"fieldtype": "Text Editor",
		"label": "Applicable Standards (Narrative)",
		"insert_after": "ic_about_testing",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_column_testing_notes",
		"fieldtype": "Column Break",
		"insert_after": "ic_applicable_standards_text",
	},
	{
		"fieldname": "ic_samples_note",
		"fieldtype": "Small Text",
		"label": "Samples Note",
		"default": "Note: Additional samples may be requested by the laboratory depending on the product configuration and applicable test requirements.",
		"insert_after": "ic_column_testing_notes",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_gst_note",
		"fieldtype": "Data",
		"label": "GST Note",
		"default": "Note: GST @ 18% (CGST+SGST / IGST as applicable under Indian GST) shall be charged additionally.",
		"insert_after": "ic_samples_note",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_section_test_lines",
		"fieldtype": "Section Break",
		"label": "4. Test Lines — Laboratory, Scope & Charges",
		"insert_after": "ic_gst_note",
		"depends_on": "eval:in_list(['Testing','Multiple Products / Multiple Services'], doc.ic_quotation_type)",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_test_items",
		"fieldtype": "Table",
		"label": "Commercials / Test Entries",
		"options": "IC Quotation Test Item",
		"insert_after": "ic_section_test_lines",
		"description": "Add one row per test. Select Laboratory → then Lab Test Scope (prices fill from the lab library).",
	},
	{
		"fieldname": "ic_sample_handling_policy",
		"fieldtype": "Text Editor",
		"label": "Sample Handling & Disposal Policy",
		"insert_after": "ic_test_items",
		"depends_on": "eval:doc.ic_quotation_type=='Testing'",
	},
	{
		"fieldname": "ic_section_policies",
		"fieldtype": "Section Break",
		"label": "8. Payment, Cancellation & Confidentiality",
		"insert_after": "ic_sample_handling_policy",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_payment_terms",
		"fieldtype": "Text Editor",
		"label": "Payment Terms",
		"insert_after": "ic_section_policies",
	},
	{
		"fieldname": "ic_cancellation_policy",
		"fieldtype": "Text Editor",
		"label": "Cancellation & Refund Policy",
		"insert_after": "ic_payment_terms",
	},
	{
		"fieldname": "ic_confidentiality",
		"fieldtype": "Text Editor",
		"label": "Confidentiality & Data Protection",
		"insert_after": "ic_cancellation_policy",
	},
	{
		"fieldname": "ic_section_products",
		"fieldtype": "Section Break",
		"label": "Multi-Product / Multi-Service Lines",
		"insert_after": "ic_confidentiality",
		"depends_on": "eval:doc.ic_quotation_type=='Multiple Products / Multiple Services'",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_products",
		"fieldtype": "Table",
		"label": "Products & Services",
		"options": "IC Quotation Product",
		"insert_after": "ic_section_products",
	},
	{
		"fieldname": "ic_section_terms",
		"fieldtype": "Section Break",
		"label": "9. Terms & Force Majeure",
		"insert_after": "ic_products",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_terms_and_conditions",
		"fieldtype": "Text Editor",
		"label": "Terms and Conditions",
		"insert_after": "ic_section_terms",
	},
	{
		"fieldname": "ic_force_majeure",
		"fieldtype": "Text Editor",
		"label": "Force Majeure",
		"insert_after": "ic_terms_and_conditions",
	},
	{
		"fieldname": "ic_parent_quotation",
		"fieldtype": "Link",
		"label": "Parent Quotation (Revision Of)",
		"options": "Quotation",
		"insert_after": "ic_force_majeure",
	},
	{
		"fieldname": "ic_links_tab",
		"fieldtype": "Tab Break",
		"label": "Linked Records",
		"insert_after": "ic_parent_quotation",
	},
	{
		"fieldname": "ic_section_links",
		"fieldtype": "Section Break",
		"label": "Lead · Project · Invoice · Testing",
		"insert_after": "ic_links_tab",
	},
	{
		"fieldname": "ic_links_html",
		"fieldtype": "HTML",
		"label": "Linked Records",
		"insert_after": "ic_section_links",
	},
]

PROJECT_FIELDS = [
	{
		"fieldname": "ic_section_stage",
		"fieldtype": "Section Break",
		"label": "Project Stage & Assignment",
		"insert_after": "project_name",
	},
	{
		"fieldname": "ic_project_stage",
		"fieldtype": "Select",
		"label": "Project Stage",
		"options": "Project Initiated\nCustomer Documents Pending\nDocuments Under Review\nApplication Submitted\nSample Awaited\nSample Received\nSample Dispatched to Laboratory\nTesting in Progress\nReport Awaited\nReport Available\nCertification in Progress\nCertificate Available\nDelivered to Customer\nProject Completed",
		"default": "Project Initiated",
		"in_list_view": 1,
		"insert_after": "ic_section_stage",
	},
	{
		"fieldname": "ic_priority",
		"fieldtype": "Select",
		"label": "Priority",
		"options": "Low\nMedium\nHigh\nUrgent",
		"default": "Medium",
		"insert_after": "ic_project_stage",
		"in_list_view": 1,
	},
	{
		"fieldname": "ic_column_break_1",
		"fieldtype": "Column Break",
		"insert_after": "ic_priority",
	},
	{
		"fieldname": "ic_pending_action",
		"fieldtype": "Data",
		"label": "Pending Action",
		"insert_after": "ic_column_break_1",
	},
	{
		"fieldname": "ic_progress_percentage",
		"fieldtype": "Percent",
		"label": "Progress Percentage",
		"insert_after": "ic_pending_action",
	},
	{
		"fieldname": "ic_section_team",
		"fieldtype": "Section Break",
		"label": "Assigned Team — one or more people",
		"insert_after": "ic_progress_percentage",
		"collapsible": 0,
	},
	{
		"fieldname": "ic_team_members",
		"fieldtype": "Table",
		"label": "Assign People",
		"options": "Project Team Member",
		"insert_after": "ic_section_team",
		"description": "Add everyone on this project. Mark one row as Primary (otherwise the first person is primary).",
	},
	{
		"fieldname": "ic_assigned_employee",
		"fieldtype": "Link",
		"label": "Primary Assignee",
		"options": "User",
		"insert_after": "ic_team_members",
		"read_only": 1,
		"description": "Auto-set from the Primary team member (or the first person listed).",
	},
	{
		"fieldname": "ic_column_team",
		"fieldtype": "Column Break",
		"insert_after": "ic_assigned_employee",
	},
	{
		"fieldname": "ic_deadline",
		"fieldtype": "Date",
		"label": "Deadline",
		"insert_after": "ic_column_team",
	},
	{
		"fieldname": "ic_quotation",
		"fieldtype": "Link",
		"label": "Source Quotation",
		"options": "Quotation",
		"insert_after": "ic_deadline",
	},
	{
		"fieldname": "ic_section_amc",
		"fieldtype": "Section Break",
		"label": "AMC / Renewal",
		"insert_after": "ic_quotation",
		"collapsible": 1,
	},
	{
		"fieldname": "ic_requires_amc",
		"fieldtype": "Check",
		"label": "Requires AMC",
		"insert_after": "ic_section_amc",
		"description": "If yes, schedule next-year contact for renewal",
	},
	{
		"fieldname": "ic_amc_contact_date",
		"fieldtype": "Date",
		"label": "Next AMC Contact Date",
		"insert_after": "ic_requires_amc",
		"depends_on": "eval:doc.ic_requires_amc",
		"description": "Usually 1 year from completion — remind Admin/Sales 1 month prior",
	},
	{
		"fieldname": "ic_amc_reminder_date",
		"fieldtype": "Date",
		"label": "AMC Reminder Date",
		"insert_after": "ic_amc_contact_date",
		"read_only": 1,
		"depends_on": "eval:doc.ic_requires_amc",
	},
	{
		"fieldname": "ic_column_amc",
		"fieldtype": "Column Break",
		"insert_after": "ic_amc_reminder_date",
	},
	{
		"fieldname": "ic_amc_status",
		"fieldtype": "Select",
		"label": "AMC Status",
		"options": "\nNot Applicable\nScheduled\nReminded\nContacted\nRenewed",
		"default": "Not Applicable",
		"insert_after": "ic_column_amc",
		"depends_on": "eval:doc.ic_requires_amc",
	},
	{
		"fieldname": "ic_amc_event",
		"fieldtype": "Link",
		"label": "AMC Calendar Event",
		"options": "Event",
		"insert_after": "ic_amc_status",
		"read_only": 1,
		"depends_on": "eval:doc.ic_requires_amc",
	},
	{
		"fieldname": "ic_amc_last_notified",
		"fieldtype": "Date",
		"label": "AMC Last Notified",
		"insert_after": "ic_amc_event",
		"read_only": 1,
		"hidden": 1,
	},
	{
		"fieldname": "ic_section_tracker",
		"fieldtype": "Section Break",
		"label": "Progress Tracker",
		"insert_after": "ic_amc_last_notified",
	},
	{
		"fieldname": "ic_progress_html",
		"fieldtype": "HTML",
		"label": "Progress",
		"insert_after": "ic_section_tracker",
	},
	{
		"fieldname": "ic_products_services",
		"fieldtype": "Small Text",
		"label": "Products / Services",
		"insert_after": "ic_progress_html",
	},
	{
		"fieldname": "ic_deliverables",
		"fieldtype": "Small Text",
		"label": "Deliverables",
		"insert_after": "ic_products_services",
	},
	{
		"fieldname": "ic_testing_requirements",
		"fieldtype": "Small Text",
		"label": "Testing Requirements",
		"insert_after": "ic_deliverables",
	},
]

SALES_INVOICE_FIELDS = [
	{
		"fieldname": "ic_qr_code",
		"fieldtype": "Attach Image",
		"label": "QR Code",
		"read_only": 1,
		"insert_after": "customer_name",
	},
	{
		"fieldname": "ic_quotation",
		"fieldtype": "Link",
		"label": "Source Quotation",
		"options": "Quotation",
		"insert_after": "ic_qr_code",
		"read_only": 1,
	},
	{
		"fieldname": "ic_currency_manual",
		"fieldtype": "Check",
		"label": "Currency Manually Set",
		"insert_after": "currency",
		"description": "Stops auto USD/INR switch from customer country. Clear to re-enable auto billing currency.",
		"default": "0",
	},
	{
		"fieldname": "ic_tax_manual",
		"fieldtype": "Check",
		"label": "Tax Template Manually Set",
		"insert_after": "taxes_and_charges",
		"description": "Stops auto GST In-state / Out-state / Export tax template selection.",
		"default": "0",
	},
	{
		"fieldname": "ic_project",
		"fieldtype": "Link",
		"label": "Project",
		"options": "Project",
		"insert_after": "project",
	},
	{
		"fieldname": "ic_consulting_note",
		"fieldtype": "Small Text",
		"label": "Consulting Billing Note",
		"insert_after": "ic_project",
		"description": "Services are non-stock — no warehouse required when selling to customers.",
	},
]

PURCHASE_INVOICE_FIELDS = [
	{
		"fieldname": "ic_section_consulting",
		"fieldtype": "Section Break",
		"label": "Consulting / Lab Purchase",
		"insert_after": "supplier_name",
	},
	{
		"fieldname": "ic_laboratory",
		"fieldtype": "Link",
		"label": "Laboratory",
		"options": "IC Laboratory",
		"insert_after": "ic_section_consulting",
		"description": "External lab whose service you are buying (non-stock).",
	},
	{
		"fieldname": "ic_testing_request",
		"fieldtype": "Link",
		"label": "Testing Request",
		"options": "IC Testing Request",
		"insert_after": "ic_laboratory",
	},
	{
		"fieldname": "ic_column_consulting",
		"fieldtype": "Column Break",
		"insert_after": "ic_testing_request",
	},
	{
		"fieldname": "ic_project",
		"fieldtype": "Link",
		"label": "Project",
		"options": "Project",
		"insert_after": "ic_column_consulting",
	},
	{
		"fieldname": "ic_consulting_note",
		"fieldtype": "Small Text",
		"label": "Consulting Purchase Note",
		"insert_after": "ic_project",
		"default": "Buy lab/vendor service for consulting delivery — no warehouse.",
	},
]

ASSET_FIELDS = [
	{
		"fieldname": "ic_current_holder",
		"fieldtype": "Link",
		"label": "Current Holder",
		"options": "Employee",
		"insert_after": "custodian",
	},
	{
		"fieldname": "ic_purchase_invoice",
		"fieldtype": "Link",
		"label": "Source Purchase Invoice",
		"options": "Purchase Invoice",
		"insert_after": "ic_current_holder",
		"description": "Link the PI used to buy this organisational asset.",
	},
	{
		"fieldname": "ic_asset_purpose",
		"fieldtype": "Small Text",
		"label": "Asset Purpose",
		"insert_after": "ic_purchase_invoice",
		"description": "Why this asset was purchased for the organisation.",
	},
]

EVENT_FIELDS = [
	{
		"fieldname": "ic_section_team",
		"fieldtype": "Section Break",
		"label": "Team Session",
		"insert_after": "description",
	},
	{
		"fieldname": "ic_booked_by",
		"fieldtype": "Link",
		"label": "Booked By",
		"options": "User",
		"read_only": 1,
		"insert_after": "ic_section_team",
		"description": "Who scheduled this session for the team",
	},
	{
		"fieldname": "ic_column_team",
		"fieldtype": "Column Break",
		"insert_after": "ic_booked_by",
	},
	{
		"fieldname": "ic_notify_minutes",
		"fieldtype": "Int",
		"label": "Notify Minutes Before",
		"default": "30",
		"insert_after": "ic_column_team",
		"description": "Desk alert to all participants this many minutes before start (default 30)",
	},
	{
		"fieldname": "ic_prestart_notified",
		"fieldtype": "Check",
		"label": "Pre-start Notified",
		"default": "0",
		"read_only": 1,
		"insert_after": "ic_notify_minutes",
	},
]

CUSTOM_FIELDS = {
	"Lead": LEAD_FIELDS,
	"Customer": CUSTOMER_FIELDS,
	"Quotation": QUOTATION_FIELDS,
	"Project": PROJECT_FIELDS,
	"Sales Invoice": SALES_INVOICE_FIELDS,
	"Purchase Invoice": PURCHASE_INVOICE_FIELDS,
	"Asset": ASSET_FIELDS,
	"Event": EVENT_FIELDS,
}
